name: Validation

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: setup apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends python3-dev \
            python3-pip python3-venv

      - name: Install Python packages
        run: |
          python3 -m venv validate
          source validate/bin/activate

          python3 -m pip install --upgrade pip
          python3 -m pip install wheel setuptools
          python3 -m pip install black

      - name: Validate
        run: |
          source validate/bin/activate

          # check that the test files have good style
          black --check -l 80 validation/scripts/*.py
