name: ORSO Val. BornAgain

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 0 * * 1'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  validate_bornagain:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 3

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: setup apt dependencies
      run: |
        sudo apt-get update

        sudo apt-get install -y --no-install-recommends python3-dev python3-pip

    - name: Install Python packages
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install cython pytest build wheel setuptools
        python3 -m pip install numpy==1.26.4 matplotlib auditwheel

    - name: Install BornAgain
      run: |
        python3 -m pip install bornagain

    - name: Validate
      run: |
        # source /usr/local/bin/thisbornagain.sh
        # ls -al /usr/local/bin
        # export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
        # printenv
        # run validation via pytest (for Python packages)
        python3 -m pytest validation/scripts/test_bornagain.py
